name:                krivine-extended
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/gabriel-fallen/krivine-extended#readme
license:             BSD3
author:              Alexander Tchitchigin
maintainer:          sad.ronin@gmail.com
copyright:           2018 Alexander Tchitchigin
category:            Application
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - deepseq
  - parallel

ghc-options: -O2 -rtsopts -threaded -with-rtsopts=-N

executables:
  extended:
    source-dirs:      src
    main:             Main.hs

# benchmarks:
#   bench:
#     source-dirs:      src
#     main:             Main.hs
